{-# LANGUAGE OverloadedStrings #-}

---- Machine generated code.
---- Output of edi-parser-scaffolder

module Text.Edifact.D96A.Simples.S7143
  ( simple7143
  ) where

import           Text.Edifact.Parsing
import           Text.Edifact.Types   (Value)

-- | Derived from this specification:
--
-- > * 7143  Item number type, coded
-- >
-- >   Desc: Identification of the type of item number.
-- >
-- >   Repr: an..3
-- >
-- >    AA     Product version number
-- >              Number assigned by manufacturer or seller to identify the
-- >              release of a product.
-- >    AB     Assembly
-- >              Self explanatory.
-- >    AC     HIBC (Health Industry Bar Code)
-- >              Article identifier used within health sector to indicate
-- >              data used conforms to HIBC.
-- >    AD     Cold roll number
-- >              Number assigned to a cold roll.
-- >    AE     Hot roll number
-- >              Number assigned to a hot roll.
-- >    AF     Slab number
-- >              Number assigned to a slab, which is produced in a
-- >              particular production step.
-- >    AG     Software revision number
-- >              A number assigned to indicate a revision of software.
-- >    AH     UPC (Universal Product Code) Consumer package code (1-5-5)
-- >              An 11-digit code that uniquely identifies consumer
-- >              packaging of a product; does not have a check digit.
-- >    AI     UPC (Universal Product Code) Consumer package code (1-5-5-1)
-- >              A 12-digit code that uniquely identifies the consumer
-- >              packaging of a product, including a check digit.
-- >    AJ     Sample number
-- >              Number assigned to a sample.
-- >    AK     Pack number
-- >              Number assigned to a pack containing a stack of items put
-- >              together (eg. cold roll sheets (steel product)).
-- >    AL     UPC (Universal Product Code) Shipping container code (1-2-5-
-- >           5)
-- >              A 13-digit code that uniquely identifies the
-- >              manufacturer's shipping unit, including the packaging
-- >              indicator.
-- >    AM     UPC (Universal Product Code)/EAN (European article number)
-- >           Shipping container code (1-2-5-5-1)
-- >              A 14-digit code that uniquely identifies the
-- >              manufacturer's shipping unit, including the packaging
-- >              indicator and the check digit.
-- >    AN     UPC (Universal Product Code) suffix
-- >              A suffix used in conjunction with a higher level UPC
-- >              (Universal product code) to define packing variations for
-- >              a product.
-- >    AO     State label code
-- >              A code which specifies the codification of the state's
-- >              labelling requirements.
-- > +  AP     Heat number
-- >              Number assigned to the heat (also known as the iron
-- >              charge) for the production of steel products.
-- > +  AT     Price look up number
-- >              Identification number on a product allowing a quick
-- >              electronic retrieval of price information for that
-- >              product.
-- > +  AU     NSN (North Atlantic Treaty Organization Stock Number)
-- >              Number assigned under the NATO (North Atlantic Treaty
-- >              Organization) codification system to provide the
-- >              identification of an approved item of supply.
-- >    BO     Buyers color
-- >              Code given by the buyer for the color of an article.
-- >    BP     Buyer's part number
-- >              Reference number assigned by the buyer to identify an
-- >              article.
-- >    CC     Industry commodity code
-- >              The codes given to certain commodities by an industry.
-- >    CG     Commodity grouping
-- >              Code for a group of articles with common characteristics
-- >              (e.g. used for statistical purposes).
-- >    CL     Color number
-- >              Code for the color of an article.
-- >    CR     Contract number
-- >              Reference number identifying a contract.
-- >    CV     Customs article number
-- >              Code defined by Customs authorities to an article or a
-- >              group of articles for Customs purposes.
-- >    DR     Drawing revision number
-- >              Reference number indicating that a change or revision has
-- >              been applied to a drawing.
-- >    DW     Drawing
-- >              Reference number identifying a drawing of an article.
-- >    EC     Engineering change level
-- >              Reference number indicating that a change or revision has
-- >              been applied to an article's specification.
-- >    EF     Material code
-- >              Code defining the material's type, surface, geometric
-- >              form plus various classifying characteristics.
-- >    EN     International Article Numbering Association (EAN)
-- >              Number assigned to a manufacturer's product according to
-- >              the International Article Numbering Association.
-- > +  GB     Buyer's internal product group code
-- >              Product group code used within a buyer's internal
-- >              systems.
-- > +  GN     National product group code
-- >              National product group code. Administered by a national
-- >              agency.
-- >    GS     General specification number
-- >              Self explanatory.
-- >    HS     Harmonised system
-- >              Self explanatory.
-- >    IB     ISBN (International Standard Book Number)
-- >              Self explanatory.
-- >    IN     Buyer's item number
-- >              Self explanatory.
-- >    IS     ISSN (International Standard Serial Number)
-- >              Self explanatory.
-- >    IT     Buyer's style number
-- >              Number given by the buyer to a specific style or form of
-- >              an article, especially used for garments.
-- >    IZ     Buyer's size code
-- >              Code given by the buyer to designate the size of an
-- >              article in textile and shoe industry.
-- >    MA     Machine number
-- >              Self explanatory.
-- >    MF     Manufacturer's (producer's) article number
-- >              The number given to an article by its manufacturer.
-- >    MN     Model number
-- >              Reference number assigned by the manufacturer to
-- >              differentiate variations in similar products in a class
-- >              or group.
-- >    MP     Product/service identification number
-- >              Reference number identifying a product or service.
-- >    NB     Batch number
-- >              Self explanatory.
-- >    ON     Customer order number
-- >              Reference number of a customer's order.
-- >    PD     Part number description
-- >              Reference number identifying a description associated
-- >              with a number ultimately used to identify an article.
-- >    PL     Purchaser's order line number
-- >              Reference number identifying a line entry in a customer's
-- >              order for goods or services.
-- >    PO     Purchase order number
-- >              Reference number identifying a customer's order.
-- >    PV     Promotional variant number
-- >              Self explanatory.
-- >    QS     Buyer's qualifier for size
-- >              Self explanatory.
-- >    RC     Returnable container number
-- >              Reference number identifying a returnable container.
-- >    RN     Release number
-- >              Reference number identifying a release from a buyer's
-- >              purchase order.
-- >    RU     Run number
-- >              Self explanatory.
-- >    RY     Record keeping of model year
-- >              Self explanatory.
-- >    SA     Supplier's article number
-- >              Number assigned to an article by the supplier of that
-- >              article.
-- >    SG     Standard group of products (mixed assortment)
-- >              Self explanatory.
-- >    SK     SKU (Stock keeping unit)
-- >              Reference number of a stock keeping unit.
-- >    SN     Serial number
-- >              Identification number of an item which distinguishes this
-- >              specific item out of a number of identical items.
-- >    SRS    RSK number
-- >              Plumbing and heating.
-- >    SS     Supplier's supplier article number
-- >              Article number referring to a sales catalogue of
-- >              supplier's supplier.
-- >    ST     Style number
-- >              Number given to a specific style or form of an article,
-- >              especially used for garments.
-- >    TG     Transport group number
-- >              Additional number to form article groups for packing
-- >              and/or transportation purposes.
-- >    UA     Ultimate customer's article number
-- >              Number assigned by ultimate customer to identify relevant
-- >              article.
-- >    UP     UPC (Universal product code)
-- >              Number assigned to a manufacturer's product by the
-- >              Product Code Council.
-- >    VN     Vendor item number
-- >              Reference number assigned by a vendor/seller identifying
-- >              a product/service/article.
-- >    VP     Vendor's (seller's) part number
-- >              Reference number assigned by a vendor/seller identifying
-- >              an article.
-- >    VS     Vendor's supplemental item number
-- >              Self explanatory.
-- >    VX     Vendor specification number
-- >              Self explanatory.
-- >    ZZZ    Mutually defined
-- >              Self explanatory.
simple7143 :: Parser Value
simple7143 = simple "7143" (alphaNumeric `upTo` 3)
